apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ""
    CLOUDFLARE_APIKEY: ""
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:CSATdmA=,iv:TfWTjqNTqrArl7zQp/gAdnSR28KTDR6cjkwZwAyPx+k=,tag:q3ounYACGycLAJx+AzM8rA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NUZ4M1orVkhYaml2OHZa
            am0wbnlac0diYTU1MDA2VjRNUllMdnMxcmlzCncvcUNtTFdKSGRHb0FIU3UvOFBz
            cE5PUjJJK1pEamdTWXVnQlZXZ1JlRUEKLS0tIFpYQWZCNUlsOHRwSjN3bzNDSWpr
            K1JFSEF4bTF4bXd1RXpGZCtFdTR0djgKLvcWLHLreVriz/IxHbLgmkcTzXZluY+R
            EDuSM+2nk1JlBHAArpl3iAVwCVN84N5zbrnJX5G1RxlFatCwSh2kHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T00:10:49Z"
    mac: ENC[AES256_GCM,data:qO/3Czjo+ynljdV94jCR5iWJrUkFsjN/WIiPiaaA2NjAsv4U1r/SWeMqcwKkh0zGODiRSwERQE++t7dPjqkjrMLeOP+shVXVHHlD8hR1E9UlKi81dOdnow5aAKeqcxO31A4XuDLreYNbxHMKr2bX0vqsvl1fW+u4LxXLif+tjDI=,iv:wA8+8Ovrv/9L+KDzqn1mkY3Ve1tmT7k7V60RG88yYtE=,tag:f/sshgegU3DsdaDBG89IfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
