apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ""
    CLOUDFLARE_APIKEY: ""
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:TRbcaTI=,iv:L2r47LaTSANFlugNpxrSsCddWdOEY2MpWiy5S4IGZxI=,tag:aVyNe4qB3otsXYL5Jj2V0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa2F1RW5mK0orU2R5aHlr
            NjU5RXBoa25vU0tvN3ZKNE12cGREZkNsMFdRCm91TjhETzduS0xrYVZreTdSVlRa
            ZVFVTHNYa2x0bG5yRTJ0bU9EQnZHSmMKLS0tICs2UTFXSDJwRUdrUEYxanJLR1VN
            WjhKSlI0a0RXR1ZEYTVHYldXNGZ4eWsKK15LiR9PwiBo/kX6Rfm6BBb3iJlAlaQH
            J8NLzoDbHaJayJkCW8LjjZHMoM7Unu5lvO9dQZaX3wEx82My706xdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T23:17:39Z"
    mac: ENC[AES256_GCM,data:ppU0oej5+gifqYRZ7Ighna1+aSw/V6ifnyIZ7CT50yIwcv71pCOpcyuXMa7JoSaK/zjNknIgrJry5UZKveBfuzhA426kuOop68yxqo1AINtFN9H6ncZxYfDVToF54FwL+Shx1zddNtBGy64IYtkpQgpPnL9wmOyrtUp9qZYsVvw=,iv:Bf8eVOtGbFzNasGVeKxCeDtShb05BSOqEQkOXOs9H0c=,tag:DEXcDe0jisE6Wq0dsHt0Hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
