---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-operator-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 12.0.0 # Renovate will bump; prometheus-community publishes official OCI
  url: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
