kind: ENC[AES256_GCM,data:agxR090C,iv:NgdzAyTGEiU2o4zzR+zO2OP9DyFWCebJ5u2R4I6GSnM=,tag:WhpFrF3h4F46vntDUD1RBw==,type:str]
ansible_user: ENC[AES256_GCM,data:i/LX,iv:y2d/Lbr86GEnLEogUXtFXoNuBj31G3EfGWZ94EY9Gbk=,tag:sYvqkHm9KkztQ0aJgyn61A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:CO3t410Y7gJDG3lffCIZGw==,iv:VVOo6r61Jwe5KWL1hzg6L1hITSEl4OLn7vjVX38UnoE=,tag:/2QlXRlRdsGvQvQAsFMtiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTlBwQTg3U3IrWkNhV1BQ
            OGR6STI1ZEFPRVF4THhYUk9DQlY4U1RiWGlRCkZ3dGd0d0wwL2FmUTRsMUFHTFZr
            Wjc2VHdDRDd4NFJxUGN6RXhXbi9mS3cKLS0tIGk1TitscDZxUEFXQ044Y1RQZ2Nn
            SHBsby91aXF1Y3RDQ0gyS2JpbWcyYjQKuahrJlamRkxu4q9TFUi/b81NIDlwBD71
            bitk7wJky0xf9rEoQyCUqH54k35hf4PPBZ0nKD/Zsl5sresi3Tj+Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T00:10:49Z"
    mac: ENC[AES256_GCM,data:ywUSi9CG4qD89d3gENOmKHhlgQPI4torB5XstzmREkdsIAB0igkdvxN1XhBgjAbY7Pa1kUKdKMILm5xRhrE0kD0O9tqrlgnMeoxZxqS4tplz4QABE/Jw+OkqoE4RH9NlF6K5ct0y7s499wCJyK8YcXbRsUUiiFcH08GjunT7vRs=,iv:psdmnaXEhjMm1DJ8V2hoIBR6WMpDs4VfcpkLQa6+Arw=,tag:2BNVDKn+Uq9KWKbVKR1MLQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
