kind: ENC[AES256_GCM,data:yyzYWx/9,iv:K0T/aMmBLWuUxZL6JJ8aECd8j+aCAgIyZF7gjxqHryg=,tag:NaZhzQ0EcRkx+oL+Ff/j6Q==,type:str]
ansible_user: ENC[AES256_GCM,data:xYxO,iv:/DR8SjqmbKKCdDlgxa4/yt5nhqk62VdgDFGvmS8ZVdg=,tag:9CNLZyiCAIuDdC8FJN9FFQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:SsokDygyzsxtX7SnTa5DYQ==,iv:FzgxEd6fsSW3wpxLBwV6TVYh6ej1OK1k9Kb9rJyx1kQ=,tag:FvGlt1P1LAnnnGlM3jZR0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSkpnV1E4alJRQ05WMWVz
            aWZ6OWZNL1A1WXFmczBEK0xKV1E3WUpxaWlrCjBiN2daTk5DenIxN0E0Q3grRzVi
            enVOQkM1WWVDTnRoeGVrNy9ZeEhhamcKLS0tIFRxRDF0Y1BJVmRiYnBJNGo2NENU
            cTlWdWU2Q1Q1UVBJRWR1RStnYXNnOUkKRy683cru/F0LqjprGec/oupSg3+yQf1E
            PxaliNA/WZIdLUgAISERhj5QEiPRz+vn4iJlwI3eJmsGC4EWQtfp8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T01:02:47Z"
    mac: ENC[AES256_GCM,data:ZlH/I6/hStBRUXMWPqv4j+dZmX1Hn+YwLB5ftWCBYUIshD/fe8gJjyB8aXQIBfohp+VFsm+Adn1JOcpizDcCKwW9OlsBPybAYXqMJ7VNc9gBGtzcibKi6z/0I4LtkoSHNDMa59uVWZIqXYHoVD5KKD54Q2rf2fAtjLCqkBf6v+k=,iv:eUJb6YoiJKmsqug3E1iIpzz/GrSAgO2F0gUoW6AlOVI=,tag:yeWHm3t20pwf0LrUi1gzjQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
