kind: ENC[AES256_GCM,data:UQnML7tV,iv:6bMDuLkqiUN6twvCGJ5gNkqqRgwaJZwNhLwv7vbir2A=,tag:IwmiFg3M7JXVtEvnoB3CGQ==,type:str]
ansible_user: ENC[AES256_GCM,data:AZYP,iv:8o5YJQHBKpltaglFHz/iRRgrcoMVbSydEhpjspej9as=,tag:ciHe/LOPJLAx++kGBinkbQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:WrMcpuMhUrzKXh70wuv1rQ==,iv:iiiXh0vttYj2mOzlqEKXdNf6hnTIupY7VlmPAb3LAeE=,tag:YNkNzDVbe68GK/PGvUd+5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUlpIbkU2WkIzSVVvaDlu
            TzA5NldMNFBZa0xKODNlV2dJbFNMNG5QOUdvCmlUQU5NZGpJMnV4eTBhdTZhcFA1
            bWNUbjQ0UHRUOFNaUnRER3dpRDZCdmsKLS0tIHNncEQ3aXpaSCtQbEtCc0YrMVhD
            TVVTeDdlUGlvb012ZElqRzJQV09zZ1UKHRWToKhaJJj3URjxcgZbAta1bQViBNmA
            CQxurTbGHgWL04Vzlk7MEKw5+4XsGH//fYsijuYEhkH21t/OuW1Gwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T00:10:49Z"
    mac: ENC[AES256_GCM,data:Z2P3YcU+f4j2dh/07ZygqVdnvs1BoGBPYCPDEkFZByXrw+q+0u6c8KaWT44C0bnjdfbvKljzMyLmEAA51/v+auIQBmOS4kTKI8uBe/W1B0DOIiXxT9l5tYJf0LvfF7QIyWx6ZbFPmabhd7hI+idhcnjVbt3C5kHn4snls3vW55k=,iv:Nnux6r9/tGFlLz2kxfeoUhAHOpVlUwmzSIgXOfYYfzM=,tag:IPaKK4xOfCxzZMVYsA19VA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
