kind: ENC[AES256_GCM,data:VLXel1oU,iv:R/2lq+YKlh/XTjZ22eMhwMgh+gpCt3PIPGUzzcvbBkc=,tag:m6J2A98lop5KhoveT+FkKA==,type:str]
ansible_user: ENC[AES256_GCM,data:S+eU,iv:h7TG3IZLQZhRInP4p6lW2p8IRVOn63gvDr4M8xKfnbY=,tag:LZUQrXmmWalFBMOjmgd60Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:02lE+uEXuFQ17p13EfhO6A==,iv:fLP9ceXi45ivCAeaGqZ0vOnVjclVfKohbLEvELKMYVY=,tag:9jIbDqf5Gtqla4KP81asUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aGwyOU82RUlqaVd6TGtl
            dzBwZFJyT0dwV2p6N0ZNaGUzbDl6WjBNMzJVCnQzeERuRlVjOTArUHh0eWFBVjlO
            VlhLYzR0Z2F3ZlBlWGZmeXNMTnA3QmMKLS0tIG1wUXk0YU1jbE9aK09meitPdE14
            R0prNTZiRTVrRC8rSGVjamdRUGhPVWcKjL4OmZHKYviy8nsj0VGgcZTZ5Yh1w2dI
            7y2k2DEiNcYzwOb8Cwvg4L1OV9AgYzcdykQqPGDLQMv2iCDoQ1usuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T01:02:47Z"
    mac: ENC[AES256_GCM,data:DFP08DW5281AAWM8ZaPLevxqETF2ZZL+Y6mCxtESIiU12nJxP5iCfORTCEkDVmMcgwVRXL1/JSmd3Lavk/+xyCcJMic0BJXHHt8uQWkShtfV4SyiPH264LzzSoBWFyp80wc51lFa3yxOMQMN1kG1lA7sXQthImyHh/m8/cMkPTI=,iv:tYSgAoiLeCKA1TqRp+5MbkZBCpoEQDGblVtuGUiUYQI=,tag:4GgwPg5Ag6ghcHeVY8GPCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
