kind: ENC[AES256_GCM,data:9/0Lntml,iv:EIbDA4U1HyqwTRSkBTfnfMqMk4SluJhtaDKTG3l9Jcs=,tag:ZNu9GXmkAburc5xtFHPTrw==,type:str]
ansible_user: ENC[AES256_GCM,data:/1S6,iv:s9uFQFuPl4CDD51RiC9W+v/mjVt5GpFdNPAxVzEuMUI=,tag:Ank94NqPTv/9IHl00DMMzA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:0zmBhQy5WOIpImClLUnAcw==,iv:cLHBHg9h30QDx5LVSJdvm01IHrmg6h3LGCgQFzle0KU=,tag:clxEg75aD3uzQfUsMhi8ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN1U4MDhBVXgxYmNjaE9a
            dUt2MFYvQjBwRlkvQk90UnMzenUxdmJqK2lZCjNuU05PRFU2QmpEenl5dkNDbTlH
            YzlLWWxJR3p4QnRGbEZSSkF2L0tZeEEKLS0tIDd6SW4vZ2dTWFlDQitwMndMenU3
            MTFnVmJMT2ZaVkdPalhMcVY2clhBb1kKeOCiU/vBylPL17ifuorOAivdOyiQcj0B
            0fHdKdBk76SyNgftqW9T+O2jVequuK47BHS9Jdw5k0XB04df7LgFRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T01:02:47Z"
    mac: ENC[AES256_GCM,data:Tqu6i9cF/Ts0ydVYRImLjBTnXQd40QhWeUuNwOj2XyFhlIJR5qVcxC4huHh51/bid2M5RlAPKkyd4rv72a+w7sw3KepgSFdrJPDAevOlKOVXK9PgXW8vrTmhsOQro/1FXUn5AVHdBySmhDSt2bp7shnLAvD7GoTaMm6wg35TtdE=,iv:q6ym4lKw3ENTzcbMHF2sFdk5fEeDp/XZjkDern1q5q0=,tag:nfACFeNLyFOL9T49BjcPMw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
