apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ""
    credentials.json: ENC[AES256_GCM,data:8cwIyhcT5gk9Rcoa8KM7u4zr/kVC6XEWIaE0j+Pg1bC/UTdq6DCB7ClzOerJc9wQaIC/gtSDWZeU5pudM8Ix17Bjx0NviNwrME9+yVjVfyBY3pmoG+P1u4HfBvH2nEc=,iv:bBQZXn2PMu5Syf/y7UWvbyV/+utGQ9vUWyiFBI+3JVw=,tag:igktfbAug+oVaykp5RC3CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSWVTNXBYTWJETlgvMXFn
            dTl6SDUyTGRkTEtPSGhSUlVDUVpKRjVnTmtzCk10QjB4dklzS0c0aSt5alZnTC82
            R1pZMXZMYjR4dlFuTTd1eGQzRTBsNDAKLS0tIGwzQnQrMVB3bHNhRjN5QS9iR0NK
            MHlxQTRSMVp2NStnMklncjA0bjBoMFkKxA5LzZMXOIpMNp5m2/ESi6HFdqZaeZN0
            EKtPohoOBvqXZuNQAwl9zl1GtWZcnu/xwR1QycHIYe1A9uNRoMzEVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T05:50:50Z"
    mac: ENC[AES256_GCM,data:MsfepveQSSepbSEyrSBwvmCAfr+WtfxJQasx19fRxaQjBKLWmtfmaPVjEi0pxRKxfG+SAh0kJPQWu/WiXV3LyogV9Ei/L6/BTVdMbAhnQRUxs4sy99BI0X1uUrZKTjEpx79quXFsgXtAmj0nKtunN6BOwyDe5RhKBg6mFdWH2cE=,iv:XU8d/rTIFODwDNK4yjOED46ZoA7X/m+SKGtqoWQ5MgY=,tag:j1j8mU7DrD0QMaYLizktvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
