apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ""
    credentials.json: ENC[AES256_GCM,data:NRUaLO+NagjFIHW3xR1W9h087ThtXPrZxRDf7r/gxqvXMEqAfnypuVdvQbczPjtsNoRji3dEGNyRJeoUlBCZSVwzqHmiIpdQDEAeKzNBK//iq+2+Gz1Rl4xJ1NQPKnU=,iv:CFZ0PO6fz/4M9o+rq5co7FbzNKuhph74y47sNrKYQS8=,tag:ICIE6/3KvyohWkhCYiYKUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19teh088u80fevs4tja0pyammvuuznznlejwz6xtnfujj6e238amsyy0jef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTU5hdE5WUDdGcXdkdTRF
            MjZBZ1lwN0lSZ1BnaDJxajhYRktnMlpMZFI4CmtReXlKc2FMaE9wbFpCbm9VMzlQ
            clpTQlprUW5VcDlZUFMveDZWTU45em8KLS0tIHNaUWlMOEpmUnVFZzExQjkyREhV
            QmY3ejFFVUFNbGd1YUpWYUErUTRuYUUKm3CzBDfJyeIdNAabJcRzxvyjD1ngG6fK
            tM9HJPxZAhVNvnkKv/v0LdBDPMHo/c+V5AjAzQTDNdIDRR72vGL7bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-04T02:22:38Z"
    mac: ENC[AES256_GCM,data:zTH/LLTl1S7JyDvHN3FwmpO9DihPr2YH4dN8TDzKMlxjXMrcj8OjhRaGcddoYYKEZ46ITx1lZlg3vXQyNG1DhGSz1FpFa+KYJFpnLj0/J9/mtojqbRwe1Ya2c0H/XyWa0L304fzuJPjGtVZ3JNJZFkxaajmxvbUYseTBVudSwcE=,iv:4tvevXkJo3miilM4cyvN7YxYq1tt+vYDw1nd1NqmNgQ=,tag:LPjOg+l8+vjxuZ7R1lmxdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
