apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ""
    credentials.json: ENC[AES256_GCM,data:8D5iwmpJX5PItyascsDVXIsvIpcEHeAnc0mmYgYl84HF2t1WG9jokf0qNz65iCE7/TMpXB40KhXOEepf8rlk9eHCnqTEmG9fUBXj4WdvdQF6tIe4veDL3tZBtkkZndY=,iv:6KQuk4fvxvse3vskboG6IgK6bLqqjWyD8x2M9II5Avs=,tag:GPQT7vbYZyGd5ZBo+kAGJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MVhZM2U3RjF0bXlUVWh6
            bUlvMExXVFNrWWxqdDIvZjlWNkZ5THBtWWhJCkx2SEJTMDBsUndnekEvV21nN2ZY
            UlpVMTB3ekt5dWEweUZzYURTVFlRRFUKLS0tIFI2d1hlMWZ6U0dTNFcyeHZzdkZE
            WDRvdXAvVVc1Vi9OY2RuQjRnakZDVW8KA/dQtXIRxDq3RfPABJ1f/Qb4H1zWviYY
            o1GqJlHtHZt/4L+NW4C5YsYwc9qDJhZSAMSSRT3PImCALp0yYOBfJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T20:38:55Z"
    mac: ENC[AES256_GCM,data:1YqpfwSGpF0iPHvr+S6u/wMYltllTSm6nBK0y42V6Nz7TgLphyC68E+6dYRxP4nr4aCixXwzbQO8lEBKHXe9YenxsRLgt4KTVkcncbK3OIl7FjiOdV2j5jlUKi9ReJf1tT8p9Qn6X7szyDwLy854Zcp0SuMn2p4CPZGSRnZYhu0=,iv:Ec1HRW6wZvpjCxjOCZhcV8ccgtkNb5S7zp7gF4rSko8=,tag:1V+IFK16YtkzkGdtcfclng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
