apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ""
    credentials.json: ENC[AES256_GCM,data:TdRw1yuNh+xwIdkDY8/U2YXqPcAWvQfzCoc/Ty2HsLzGUqAiFP/Lhf5SmmcMIgPOXW7B1444noNCM+L3mIhk7+fxUHezKfu2Amt7SRTr05OQL5kIVE+676cDYVid/2w=,iv:bc0Zf13k1FN4TdEZyjW3jwAVe4HWxxLycFWw1+L7fCo=,tag:N6TlCdjGwBUYcLk12ratRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXa1J3NUNUOUtvWFlsWlNp
            L1pOQnNMQXQzLzFjdVNGNzYyQmpoU3RqV1VjCnNrcXFUQWIzUHo4V0xVaVh1UXE2
            b2c1Z2ViVHQwK3NBc3N1TFB1a243a28KLS0tIDl4R0FxSmhQSnprbkpIM1VoMEdR
            T1hmdDZTcU0yd1c1WFhwQmZIdm52d1UKtcs7cpxgSo6tSWAavR7StIUODfNziQqP
            ikDYHhtLA5KfVLiCOYezmDegGS8QLCaXyoYYa7EpwOdbMfInbiC3bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T02:06:50Z"
    mac: ENC[AES256_GCM,data:ZJZyWcFuA8FQCQinxXC8kTInjFciAwoU+ARFwwuTSJSbJwEqmHTHHxBjjjCaB6PEgznX8Mp8n3baTBKp053fxbThr9tlPtwzxgUXwuocM/slBfWkc2Zl/1591nRj5BymRiw5i/cVBHhUvtEvW/AbLPWeIRDECb+LCVAHOlKcmvw=,iv:V3Naa2WTS6vVdnnx2vSRuARXFyF3MBei12SLb+6XEG4=,tag:dTgxPvU+m7MiMbdbOhsxZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
