apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:z1nr0utg4YlW1ZuIGHF1q/vFufcEc48VSPmiOqIAqcpF+GUCUbkEYg==,iv:kIwPxH4BYFZ6HK2s+Ku4pGvpELraoKFsHYfRRuAB2+A=,tag:PWNQJpmLt8QeRG5JjHa+9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN1drV0FvNGZReFlqYVdN
            dGo5dEYyL05iZTIrM3lWQ28zajhObm5iOFU0CmYwQlQwRzFZek5BSWd4a0U0Zi9m
            RlZlWSs5MndrZkpNTFJCSEZmUkZXWVUKLS0tIG9tRHZCSVVJL2FHVGo1WEljeklR
            ZTdZRGkvenJJOTFNOVIrZXVLaXJDMGMKPiSqO4cZL7EFYEoATgljmEDbqHuTYmhF
            ITgS0fxuA6bm3Yby14iB/jeuGZyq4zvzIPOA28PV8LiucsXxNK5Rfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T23:17:39Z"
    mac: ENC[AES256_GCM,data:k3uM7yrPCKRBu9NcS0FwB2yxFdr+D/8UC2YTopMdaRLUj5k1jTJMlZbsiw81Fwz3hjrRuE+deeEeTqjqi1qQige/5UEoU+4asuU2q3ddiDds5uoQdso0NDYHdGsspHXhuf2ldv7cPorcB5EK9VXeThPAmAbzkjv+ze6zNFSgerg=,iv:e1buuDjHt2ADUp6khRJgjL8pi7vEB5gxdCSkIgnXNCA=,tag:IMhGsv2xKGtwxt/yXPZ1Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
