apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UJ2OlSsW8OJ+Vj7ouM3M8jeXbgDbGC1lJor+sr2CmHcsmuCbIF5dnQ==,iv:Nw21xc02UEuZbdEZqZwMKIqv54sW1qZbk4UH81H9Ofg=,tag:mJ2RiXD3okYyk4N9XGU5bQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNitwYTQ3bDlIRk9QNm1T
            dnlsajRybjdLYWFGbzR3Tzh2ejdjOXV0VnhzCkU0aGRKKzlYV2dRcTdYeHk3bFdt
            aXpmdWJnZ0VLL0xDcEVRSEtSUC9RYXMKLS0tIHp6WS9RQjBhQjdYSy9rNHFPMnBn
            MVpEMVJqcXB6SFovQXNYaG1IZWl6SU0KNVuJN6KPysomDE5n+uQ7CrtnJt8ZSG1Z
            qwI+j2w/RWuskgj4MNbPkuO9NUcacu9sLIAKMMEXz76ho1EdDZBeZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T00:10:49Z"
    mac: ENC[AES256_GCM,data:CGKH3aV0eG/dT2KAw7YXtCL1cRgWzKx/YTlPsNC4RYKk+1cdsNIrwWrPhVZWy8nUEyvllLys8Zt/j92DpqRYXomL0Jum6RTOwxB+eT2MkzztxGp3hmHMByB165I6nt8B0jJbFjdbKveog3FrF6K9mItOt8dQJw/6c9q0FincWS4=,iv:XABuLunkSc9bKVF4mELd+JNhBlugeN3e1Si/d6RDcyE=,tag:Ixyxt9oHI41HjHuFWYjajg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
