apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: observability
stringData:
    admin-user: ENC[AES256_GCM,data:yGeSfxw=,iv:MsgyEq/yfoZQ+noiXGT6gH21D8g44FlGHgQRDOT/XkI=,tag:SNcxOsHg0nR+zQUNaTBoRA==,type:str]
    admin-password: ENC[AES256_GCM,data:v+Oo8Oi3bYNzo9qdBV5XKGovDMDm6cS7mvxEDPau1U4=,iv:SsZfE4xKzQsQyclNYbkJBRJxPaUbAE7shqy6owp279M=,tag:99PRrZgmO13c5d8q357Pyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaDVERW9Kamo4ZjYxbmJh
            c3Z0ZVZzdGdFWmFDQlhsbXpWOUcrajFHVmt3CjBnUzBiQlNLOGFzNVN5SzBJU3ox
            NXFreG9KMzZuSWlCL0h3bjJPTGdGS00KLS0tIFFsRmV1Z1Nzai9NemNoVmczeThV
            S0VYRTQwL3haRDIzZG5PK0JzVlpvUncKZZK//az/HyZEmcM9wV28j2oaXvAHKoc0
            KWYG4hLBAiQuCt/9/KI/sZsc3T836436IkKi0BUE/AMVJTiWuQVO+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T20:34:38Z"
    mac: ENC[AES256_GCM,data:9bvzL2u4WuHcB5mvDAW0VoQGvw7iu61qi0W3U/ATVEDy3Og1RgZ0yrp1HB50dMM3CBxZYmfvZFmCh1I5NyhGNLEbsyaSuDLbMojaDOBU6pwtRkUkMJZ12TofqEfY8rggcnwYL0ylZ+VDVgOEAN2xvQZtZ8HrLDTZCI7DkE0qvmc=,iv:XeVhtNaB2xA76YGp86cP0WCY/iK2UaJrmQ0aoG6CnUE=,tag:jQ7UBz5sIvMIx/K0uhATGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
