apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: observability
stringData:
    admin-user: ENC[AES256_GCM,data:b6FshvM=,iv:yLQGdjDpIILf9/+rJU5vLHN3PsovMr5P9Zh0ibMVppw=,tag:dmEYHA+uEY+y5StT6KSTIA==,type:str]
    admin-password: ENC[AES256_GCM,data:BVQsn0VTUkGtjfbHsc+8TfXd0hyk/t/4COuKBbRKftc=,iv:BLGXHClceCbUlqQ9/j8QtTNhdLSinQrNIwB9G0xi/YY=,tag:5zFN2HAnHMeAvqW3yP5Gjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSzJYZmZ6U0o1b1dQdEh3
            UUJJNFdud3A2QU1YS1ppTU1PeGF4SDdOQVIwCnI5OHVZZUVyQ25IdFYzZzFJM2k0
            MEtzSGJaTG9teGliN2Z6VEtiYURoT1EKLS0tIGsweHIyUVNBaFpHWWk5OGhyL3E3
            UnVTcmdyS1Voc0lYVTg3WTlqVXQ5SzQKzUvG6xFCLMs+Oy6dPQbNfSqFSzegNy0/
            CFyUN17ZF1wf/wtDZ2KjG9d7rucflaC0RakGAYofTK/BLUzS/4F+OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-24T02:25:40Z"
    mac: ENC[AES256_GCM,data:DIO7xzpO21fvlOvkhUQ9/n/SGyJD4njXHh3dRQQAoQbvg+/hObM/TZAi9pMDAdAWt2tYdf60X0sh7AgtB7TxsAtRIdwGIIQHUJAuPw5arUuPZhXL4rBxaN0Z8M5wpbc7Gk4GGUgKIZB/DwiWYQF4j1aGMAs7A40c7f9s7kYfr0Y=,iv:ElxtazE1vmHnSFL/txSbaCbW3zSGqoh4osU+1mbILWA=,tag:LxmEsnmZkdAMeILqF6CELg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
