apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: observability
stringData:
    admin-user: ENC[AES256_GCM,data:WvcAmEU=,iv:q4jBYCokd5nbuPFPIHvyoYWzAcXCr/TdRKRTG0TqtqI=,tag:h11avFotoUa7VdY1gyUWmQ==,type:str]
    admin-password: ENC[AES256_GCM,data:4BwrHV9C9Qm1EgW1QbmmRg+GtRc=,iv:3Lu0uunV0XaPyJwSsDNnpGc1loBancTJQrWhR40Hpn4=,tag:Q05M5JgvmxXfb1Nzyhnb2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINnU2Z3hwSFZzVDVnWXFR
            Wi95ekUrbHhXVFRqNEhJeGsyckVBY2xMY2g0ClVLSGZWRVNEblBnMEVjbVhhcDFR
            QVlTRmd5R2Y3djBTbkpFeVFGSTZOZVEKLS0tIFVOMy8xSW5HY0xGdUpjS1BWa0Jx
            MFEvSzVNZWhnM0NEVG5EbVdIU2VLOTgKMJyltvXeCBwHLFbDrHqunyii0PqAEJHZ
            Wg6gOxA7kGTSk/qWvTyJICTYwf7NvpNewQrbFmf6bGswNmqp2yH0jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T06:05:19Z"
    mac: ENC[AES256_GCM,data:8HGPHTuWK76Y5M5q7EmeeelXLLLzmPlPt8NewZ3+RLROAdUPizZE3udjC0xYpUI0MMytWER72xDbiJ3g8GorQaZyKlzOxP1XtKpqPsxkpq1uhuFBIsYws+OtBaU5Z2ZHaRyaZI4GRmsElbsZPyCzE+qGgyAOnJqAjfOLe/Bj/4E=,iv:KXvnCRkrr1KE292BPFEvNwMF19YP+Pl6Q6cuzs2qnuE=,tag:QirxgRuoAJE3ZgnvBZT1ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
