apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: observability
stringData:
    admin-user: ENC[AES256_GCM,data:9J00lUo=,iv:508k1KC350wAww7xauPtDh/5NxstEE2mJ7qAuRsc4Ek=,tag:3rVFU4X1hAYrI82SafaCsQ==,type:str]
    admin-password: ENC[AES256_GCM,data:6bP8Tgc1tSTkpfzrXMxZ4DtURn0=,iv:QTom7sCafvgOQ8bCEBevUp5mskF3+YeX6GqF67Ot++0=,tag:V1kfne+uO3Ir3gZsPDMkKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4anhpVHcvVUlORUUvNm1B
            QWQ5eCsrdCtzT3pyTm0vcWNRdUpzdGtZUmdNClhJMldrNXM0eU9wQVRLUkw1elJu
            Z2MvdU9kUWdudm9NS1dmbmlqSmV2Z2sKLS0tIFBMRnN5Mm5HcXU2TUc4NktkdG1S
            VWNTRDF0Q0EzNFZOUGxNYktqUnc4OEEK99GYFJ1zjwxehiWEoqAagsErRz48HQUj
            DA9MOBDunxkb3dgggAUxNJX6UMYzKpXH2UcQEYmpDgIL3GB+O3THeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T03:57:01Z"
    mac: ENC[AES256_GCM,data:bsaifH85I4yELFRFIAG3COVvc+vuna9BIZe/diGYl9s/d1tN8Rz8zTjmfkH0Ld/evgpt0jt8LexvYHe01PzJ01N7k7fQl6eJs34PsK9hf2iXENHHQBYz8gKIpBXAV0g4l8IhN8s8qYeJx00b9ZsXxxG0KyI8u1N5wc4+w7MEVKM=,iv:L3bv74iOxb3DSatEUwSE32txAdHyW/1XR9Yv/LoWXS4=,tag:MrUxM1e7Ht/Hk/Z0jJtArQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
