apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: observability
stringData:
    admin-user: ENC[AES256_GCM,data:gnHETn0=,iv:Cnwi6RHvEOUmzAefcKixDdLzdwB9Aq+nVEPeSVIX5g4=,tag:ufcvoXfAmdo7S5i18d2F0Q==,type:str]
    admin-password: ENC[AES256_GCM,data:STVcLYzPVeBwoV5HneRVh572/ws=,iv:Nfy7lWs9CB9jOJCNWspuN0KnemN9WcUnc7iQ98bV6aI=,tag:OwKwrLGeZpTEBANhF5YbCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZkJMcVExUHFKek1XLzgz
            aFhpTkl6RTVvaVk5SmNIa0Q2NURnWkhVUG5RCjc3cXVIUTRnRHZwSDRzQyt0R1RN
            Q0hYaEdWNUtZK3RIRzJuTXlrVThZWjAKLS0tIHU4T1ZYekwrWFhYWjhEaWRiSUV6
            aERETEUrdVFjTVpBM2FmVkN1TVQzMncKfPWyZ48o4/9u54yEGcv121lvI1X1vXXB
            nrN6M9ea/z3nY+0Xh+WSkqDvQtK6/eqLe+EbBauwY5gjb3S5djRg3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T06:15:44Z"
    mac: ENC[AES256_GCM,data:TZxnD6FPa9s1nAYhtJlf82/5HdQ970ZB8ZZHlS/XkQfxClCWRvfLrv8sEzx/TLGCFwiiQHRKUY0NJuSedZ/LcnH7JrlnI/NtYAnhejTrCp4Am/yXBNT/Bh8jUHESTp5txFWEDFp5JsHvRUnMDQhjBzw8a3befjTEbTIU2TICPcY=,iv:uLbl333icHXUTNr8KtL+RRWKF2LiO9jZJmdUqsXotwg=,tag:B1asfEnaQNSGzcfRAtpybw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
