apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZgX5gU15m3aYD7SB4QMfb5zkwFk6hD5SrVYWjqtrUaOTY4ruGeP50A==,iv:SsVOp3sj2km6uDyNCoQp6bTYtK3VbnHdjGMlM2zzNQQ=,tag:HZKjexE0MiQFTlQlqNJSIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByT1BHa1pwRjlObHBqM0Rw
            Q3VwV0ZPenh3bG1MTkZWZW1SUng1aGFTT0RZCjZNOWUvejhlMmlpRjVOTlNyL3Nn
            TXNVbklHbm1udCtyQkhmaG0wN1ZWekkKLS0tIE41a0FXZVlidVJZNGFwSVg3eWsw
            UVBlVDNsdUVmeXBGOXppd0tCVm5oakkKqJxqhWK60N0fK4EnReZzqCurddbsBXQz
            TxwW7Ulnle96x/n77Mu4JwxdlJ1UbAnERXeHJjmqCmu4Pk2ru5RN1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T03:53:12Z"
    mac: ENC[AES256_GCM,data:8Y4YBaslJKcKOcay6ngTX8wuKMfRptyKcmKJe3N0wpjzY+xGC8YD7zTAcoNjmASuI4LtEcEH9ryTuVQ+i5XuxXKrgrU4RU/b9BWZF54zLXsgH86R3jR8jqO9tJQ+cnApD071ED+hzgbe7PC82x1fp6w5JlDXg3l3vq/ZjzEjN+I=,iv:Cx3U5awRQDICyonCgTce/jlnHXnM2FH26Cw4ld+MM1g=,tag:+HICdpEL8MthcxnRfpXvzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
