apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:o3DdXOEs3d8SGWV2NxfS+ij6b2X5fOPbRx2aitF/9YeVEh+wDv8M4w==,iv:rsiA8yb9RiccuOVz9AlHaS1BoEabnEnLsHt051cUY1I=,tag:9Pu6uEyNeQf3YhuiymgaAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNV2xHa0E2M2tSMFA1clBp
            bjVHbERmeHU4aHBSU2lFcFFZSFhSQXdsTjJrCldWaEMvdXpQMFVIQ3VuQWl1V2Fs
            alNJa09meUsxS2pKQzdWWkg0OXV3SlkKLS0tIFQxOXp1UWRabXdpYjJvVC95aWMy
            UUNObHlGZlZhbDFRcm1HOEhOZFZRWk0KLzBxlz+i21RGpRXgUszLq38UJObiBGNd
            QKnNPBB/AcnhhvyFhyKHwhqEl240rWcA1R0k78DhHY+7t7lZTZCSVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T02:06:50Z"
    mac: ENC[AES256_GCM,data:sVwu48Gif/DCo746NdirKmiy1mUNJYrF2x9KsOO/qBuFFSUae4+mzjZ0tfeLlsZikOpzfuttku0p50GxOaO+EpOJCkvRHj4KIBO9ZyDXcHHfEaG7vIKZ1hCOGt2kF+9DjZW/HNnxk6aRE5lz1DvMmbHOjB4gR+MshRMQ8Pq+sdQ=,iv:M8AI0wo9c0qBHrmJGmiY6DRlA3ddpcMTp5znA1wU5U8=,tag:KduYx0U790tyTIuMx4tN8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
