apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZTU2b1cvUnVvamZhRm5o
            dGFUMnRDdEtTU2ZWZDgremcvR3AwSWtaUUdrCkZEK1ZFQWpYUmxiQzM2ZjdYeUhw
            Z2ZQWnhLaW9mMzl5TzBQT2NqbW05RVEKLS0tIFVtWkZKbkxmbEtnZWlXS2RrRmRs
            SGtnaXB3S0wzQ1QyNzl5bmhtOE9yNkEKIOKer8SljwnAqhdIQyseSHroU1iQDfcB
            dezj1s24WCwxBuEyydMmxxZNYScyyUjvdx6SKxlbaTRxY7zuHmvrjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T23:17:39Z"
    mac: ENC[AES256_GCM,data:PEuDO1KHOBzi94qN7Q44zsltfw1OhTBz9+mg/Y6EcsSkwJrqOM9oshgt4wOEWCbGoyA/SN374D09tkDrNPh+ruilNO3lhb0kdT7wYQb6XhGz7TF+KERI7LwUEXwj2rQUawsyoFziXskuYqPjk+O/u4bxi7yC1vqbJp45WmOVMm8=,iv:2+kOrUA+abw7nJA+cDTwxk5v2rLfiECiZq5mGyIzDMk=,tag:xi9TGq7JH8tNxGCSewHjEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
