apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:WeIOjiVTxPocBF6CeTwQ8/1HuZiX4tTmuyN1johDzviYYrKpzOQ/Vw==,iv:D43DMTvk9xBp/VtzklM0zDSILBGaupWa6uxnYIJbjOU=,tag:eu7dtf7go1BKBj4KxVesqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19teh088u80fevs4tja0pyammvuuznznlejwz6xtnfujj6e238amsyy0jef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRzcxL2doMjhVUnp4Zm8z
            eTl3c0tOVWg5K0x4dlphRjZ2Y0ZGUVdJcUdjCnJGd2FTbUJHOUx5MjZaL2xaVElh
            RkZ1WjBUUjQzN0lTR0FOeDhiQXJBYTgKLS0tIHhJSEUyWXlTenA5cElTOHB1TGNE
            S0UxUVZaNWsxM1I3eTQybmhiSU93RkkKdtSrGQ3xt0TE2xoOYPi71vrSNqgKggIz
            11ksEjIWKxiGoKJunA1hNBMD1qwWLu7HsvvCdEZa/ehctEMlJbWccw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-04T02:22:37Z"
    mac: ENC[AES256_GCM,data:YtQEUNFd7WQdtqFDkkfr+6FP7upz7F1c84ZLUUlvUucyc4r8ly+revY3QZlQicCOT7GOdIcampmsH0tZnAbE+khiH+RQNHT0zfIUIBuwxs6EdXgz1zI82eWQsJyEHho7EkeyfSb6yZt1+k6LmtQYiorrM05b9HEJXW9lY/Tw2rE=,iv:7hxbuyoJp/UQcNC6xNXs62v3ecOQunU3pbhoqX712aU=,tag:Th7zkDDn7u9Kxg1CICLbAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
