apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZ1Q3K2hYd2xxN2VTa2hi
            eVVqRVhNdnY5UVdhc0F6bG5TQ3BRRkt3MDJjCmNpcS9rUW11RVV5akJkK3Z1Y1dV
            VnErNGJqdGFSVWVKSnhJcldZS292V2cKLS0tIHFiVmZBRG5UTUdCZjNTOHlZRzdr
            aGVGVS9HbkxYbzQ4a29GQ1U5eE9OQnMKB9upb346wNZxivP1ObsexT506m0wSjj6
            4kVl0JcBP30LqiEXyl2GG3WeASUqyvqXt/Afq9lylLKEdW3bNYmqzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T00:10:49Z"
    mac: ENC[AES256_GCM,data:035vJYwEfYuE96dnYPeMi+ulZUcK3AvVlBxoksny7p3G0eVlb5B78t9B50F3dRa/BubHV8ijl3o2WzJgEDzsiMnFZcu9qBFaU1GXxx/MX2fANHcrsp0Mc729kXbF0ZN6vEQiIsWuO3Zg7WHFAefLagBXlpAXpHPPGfNTVbYq1hw=,iv:u1+3L4EVHBWfuGJYZQY9uciy6OLOtIcQrgdynYzDiIk=,tag:Nm1/XKN0JdVgr+cRHOL+6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
