apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Fxsq2hSc+DCB3XahrRjB8gbGakpEaaSDt98uEc2nPqXcmPv7ANo2mA==,iv:l8i4cLRbji2Chkr0SX2G2yknDmAbHSUZkVYvIrNITWc=,tag:HrTD0i9Ee4wgOIjKWMw2Xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN0p2ZWxOanQrajRPZWFl
            WXN4emI0MDFGeGRGTVI1WW5YRGgyS1piWW1RClZBMVgwa2lZTnlDTnRZOWVFVmtE
            OFhXb1Q3KzJPUkcxb3F6L0xZdDdSZ00KLS0tIG1BaDZZRFBmOCtydmYydlN4M2I2
            eFZJYjZKVjRGS1JLVWh2NVp0eUREdFkKHWE+T5bQrAXLeCjKVdrvEIsn6EeAWXZG
            Z0Z6mdFp52WtBltY+8EnBAEmnVxv4ZQv+f9cdU5ZTtzxu8nWRr74Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T20:53:27Z"
    mac: ENC[AES256_GCM,data:clwrnU/9ZsteHxPW70NTL5X+AcoiWJaFobxQgJpUz+3yJM6u6sZ2S4sL1hX71x/LiRqGQ58NV3ommglbGY6AQBd+JJuOCB0cHWya9FUia4wgeozPQWVujpYzfRi033BSqGLfDaJaD8ER3UzPkimIMlvMq/NktrVAxLuA1qkTH+c=,iv:zm8h8xkId2CBhr+7qGNouCwZpFcYv447PSgS1bQFtvg=,tag:INHJ8c6xBY79HsVi5Xgkeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
