apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ""
    api-key: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQSszRWZvMVBQRzc0SnJ3
            M3BneVUzYVFZdGFpK1huSEZSNG5qL2dvTmxNCnkyYktrWVJRWjRFQjVoTGVMMnJF
            ZFVSenBKS3BiK0QyUzBVU2xZdmxkelEKLS0tIEwxK1pBckxDZjJVODEvZWVMcERE
            Vzl0d0dXdUVXM2VpWE92VzhlbUk2WkEKJsMv5eEDv+kwu6Tb5GkPxDspm/K7C4Yp
            JDBmt/sPsHASX/2pHgbMEZNh4E1UUa4Vw4Pl21KuxR0zrLGdfF3o3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T23:17:39Z"
    mac: ENC[AES256_GCM,data:060RuzVRAfgR32gltilgpr8yrtPIVoVv9b0gE+qmr08GPkDYXMFrofCgEs14lXxULKKOUEj4b8mMhymKEpKrTHHxSA3koirK3xARYqx4uXpkuvNj67m0AqjhZSjpWDB9WTmiUZlnKJ7kPnoGQBgFXLEGjg9DGQLIjb2E7YaBDks=,iv:9EfUoT8vtPghrZxuyGwgm3OH5BaC/DF2KXJTZkoayRI=,tag:YRJHtBbuUp8gXw19QYHiLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
