apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ""
    api-key: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQnNyK2o4Z2kwM09pbTJs
            VGNoVzIxQW00WVpSTXZZTGk1YnZvS3lSZ1NRCjE1SXRxbFVMbjZOc09TSC9nM095
            bUJQd0pES0ROTXF5alJPR09ySmtWY0EKLS0tIE9kZExpMFVRdHppblVMZEwxT3Vq
            U1c4bzY0YXBoY20vUG5WRWxVcDJEQkEKg+ezf/vhexgYqBCDlw7t2TM6jhLv8Fen
            Fl5u93ju582CFo/nuVukXdZZx9sEvzWyqz+/CH/1HJs1PRmxYCFf6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T00:10:49Z"
    mac: ENC[AES256_GCM,data:oaBKWk622gMJeL0gpmOwjNza5gNnhSSgA25DZCFnImWy4eWc2X126wWbVzkER0j2z5Js0C43WrcKU98aqisZY1Qzmo3QdDg4onwmXtJ6IY3ePSEImhB+sum+aPCwwBMUFJdIoaRPwNKxQmBWjoIdG/cZ7OFNNVmFiTTuxHUxEL8=,iv:YkW+yu2T0gCRnbOK4/KTyPyVmvQBr74qutnB7dbINXQ=,tag:+93/MKhunlwQ6dj/uWWW3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
