apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:iToETl9eBMzMsJne4Hh9E12LWsKdChpdvZvSeg72Ofu+S7KPs0tTrHtmNtsmnUQyGXJmcfDzDMPN84r9,iv:9T1Y1cAAJ8S3pJWNMXQtaF/PXpoDi+IPLHCfBnOUOY0=,tag:jyNO+NKE4QbgGeqXvcfZVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q1JtYUpMMXhJaGR5NjFT
            dWFLek84OFpTeWF0Qnhib1FqVEZwWU5xTGg4CllrZGVLcEgreUFONEIyOEM3RzF1
            Vi8yOXZOdE81QWtrZ3VCUlFNekxSbFkKLS0tIERIOTYzZGlaZ1g3eUdqbmhnZmpw
            bEFQY01pclpIcU0xVHBFY1JQL1FUNGMKcGsJQRYHrhLcU2Q30JqD/YV/6hzR3Rpp
            4brkt76wKsLldrAHvhbpvxXwZBQ8o3mwlbovzD6oPcsbJWB1PSjWmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T00:10:49Z"
    mac: ENC[AES256_GCM,data:PBpG8WmmRshmAUHDyMTh2Hn8wJADHh3QlWIFMHZHdAMb7QpEFy3KBaCNkcJnK5bdjb2jkMdmo30Fj+SoMG5BgXAiss6mC69cVZr9NUmacPtXYch5NBv8GcXkBSNUnijmlClTRduzaAdNsCQFu2H117M3ChuT4l9+EGc4AkvVxWI=,iv:acQeXzpBuCKzonDzcTLlIB2wqby988Q0jYRqBNhBPXE=,tag:mmQIV03Xuz18aUPG6JNiVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
