apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:xj0fllmjZ08TiQLqVCA5n3LwyyXCsxbTg5EfEKdbPklbIRKt2k9PylOPImCBOAL4ImzgyE1EhUXdfrLr,iv:jKiBbBuGGKUcpdA3q7aDC+T7az/4pbTTt9vkOgXateY=,tag:KrK1gAx2NjDQwLW+neyhUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVGNRS1VjRXdUVHB1TVJW
            eW9qa3dzZXh5bmNMUzJhWWI1VDlQa2dPbEdnCmtSRlQ1LzQvM1A3YkJWb1Z2dmti
            TEpleFcwM3k2QWFCWmIxOFkzSDlSdDgKLS0tIHlXajUrdlJLSE1meEQxSysxZ2x6
            cGxMM3VEd1JIUktRY1dCb1lUZHUrMkUKjj/c2Tr3o62HzlSMDhJa52s64MP7n+0C
            hbPf4M4HWGwI3dGRwFWRDuPRGwtzFteTz3fCAB4fOKqVXD+XT4Hd6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T23:17:40Z"
    mac: ENC[AES256_GCM,data:i32zUkOOl0Rml5zMuekESO1vYnnAO7xfefBoESbHYXi4WRxyT4B3NrSNqk1vu/abda94qeuKhpJrBfUPTnvw15jkLGsQfc95SnrEE1HArT9CUMtZ58JSKdjgcDQkbH/yzdC270NPUN/DFguS0v8tjv8U9huhobXKVcMt+HZzKG0=,iv:LHV2NEShdKQv+RIpVjNfzBCFj8GL7tPNuLmH0A7ypjo=,tag:Z8J0xAOqHHho/mDbO8qMhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
