apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:rT26NAEjR14=,iv:JEQ7MSTHXIJL6iYOZwg2jClBykZMSdfA06ARrNnh12s=,tag:TSR5wNIiAm+ziqscQ2dg5Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:jANZf0Teo6LTx4bLL5ri,iv:gmaF5G19XOzfWpLl6WDTN9CXB3bqIYMX5gg3LiEzFWA=,tag:QXZGAmxKpcWeQjol7/MdZg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOTE4UUF2dk9WSTlvZVla
            cnE2eGVETm9rQTJPMHB6M016VWtJcFFqN3pBCnZFbUJnRGExdWI1TkpvMDJEV3Z4
            MVdrN0ZNTFplaW9PZ29meFFHVmtZVHMKLS0tIEhNN2ZQS0tiR2hpRkdZRVBqM1RI
            Ni85L1NQVlNaK1RTWGNWRi9DdER0dVUKjTMmM4+xSk4Sjw1h9NztIQYWhZgiiAM0
            Vhc0QZ+RQETgy9yJfXU3ruPH1OFfayewLrEmVghc6zCKn8BTVjYhqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T20:38:57Z"
    mac: ENC[AES256_GCM,data:HIByCKgaFPYegirUVX81GpPzF0vSY0wYucgDXVc6+ZNyELs9+yAejveoWoUFIIY9cKMwQjICOAFCZ7oetKXKL7lSGjntLHYRL4z/SHJK71EfggEFZ6w3FzEOFH1nIHn92FbHGm3p7vstKtap09yfada/nZ2kC1ttxqxp1k8g2dY=,iv:Y73I7r3OlucXUT/hXafOpt/PgFhPAu2+S1mt9llaSfY=,tag:FQBCKWyjkGa9WItSN8Gmag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
