apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_CLOUDFLARE_EMAIL: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTHJ4UjVOdmJ6dGkyNzdO
            dSs2MHg1SWpKTVlBQ1BqMFhZQnZ4Sit3dFJ3Cms5eVZrNWFoODZyREhXeDIzQzFo
            L3U5Yjc4R3BMa203TVhNeVZCMDVkVUkKLS0tIFNjVWdndlFHZks0andlUGkrdXk0
            aFcxemNkaFlHNjdjaE1kVUVjUmdMK28K1USfhZnEB8q8xiZ8+Zx3rwZ4uP/eXR95
            NrOu7jOuPl6OGrcQwEabaB+fBiTjICN8J/RW9B+8jkkdU+KK/oIeQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T23:17:39Z"
    mac: ENC[AES256_GCM,data:2iVQBAAbnjtY/zj4xQOqb3BBehEt6kUt8kGELoS5RuzUEIrVl1D1vw7ZxVjfPufb8mu2ck2u4obLLYkWVjmafnG+HWaf4lA1nUx0Yn3Q90yUzINoPJntcdtx4CdXCL4fXFffvejSyTEoW1mJk9WYkkeCST/jyYGKcWYsZJK7cP0=,iv:j3wmnDbQvL1//6b47cCyEUrkZSYSLJ64ixHrG0xUtlo=,tag:3J/jX+s04SjBYqbRxPtRcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
