apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:24QrloxCdxngi70=,iv:B0SVbjyGDC+zF5YzgnI+PLWLr57GzAxrbxxPoO1I84s=,tag:CWIqaxpj649dU0/yk3xtng==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/OPafYWFBWclwm1ZOodj,iv:qR41uB6GJV5tKsABZ7EI8z43HI/AU9+qC1VL9FNMdBI=,tag:zf771bjgrBnGluxEfF+nWQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdSs1OXV1R1EzWnNSVFhM
            TUloVnRMVG9SUWNmcGhzQ1FtS01oSFd5akd3CnQvSGdMSXQzWnRVRE40SUtINmJZ
            bTYwMFFqajRTWGJaNUlMVEc5Ny91b2sKLS0tIGpHTVVTcVVEVWhRaStxYkFHU3dx
            Tm1pUFZ4Z00vUHNmQW5XWlhqbXk4eFEKnvxzbrEfp9G37oCOeseXAd2A/mx5Tklv
            Q3THU59olzRwz1mm61dN318OaTve20Vm8PNsIql6w8tQkxpc1yYtwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T03:38:51Z"
    mac: ENC[AES256_GCM,data:RETzMIXG0jGUctfdUBFlysCQf/+9zdb6R6TEMmY39TKznYUF1tm+orCiRBJS9twM0HeHKBew0xmgLsr6x8R9SozGNZNK/IUolYZm43DCC4uh9ycoNypmG9uB+ttdsp4gES5uLNJQBpXiZUHoCNv2Z+WGxh6oRZIP+0lQIxheFII=,iv:G1vXE4omz8t2lVGOxcKYXnZQrzfzVNJ+ibscTxGvC5o=,tag:OVFHM4TkMPy8ko9k3xDHWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
