apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:CBp9hvAyeaM=,iv:5Cu8wqtBDYyhEaTN/vmlEVtS4bh4c4IC5he8mEl8fLI=,tag:fbTHFIOzcqCqaq6E1RjW1A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:jHKfLG5+N6hbRaD+qfC+,iv:LSd2j06p8zd9+s6fwbHnMXguXeNT5uf8Kd/UDeulHaw=,tag:Xbwm4xF7FTrGWF2oh3a2Og==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveWkydjNQcitCNlFWb0VX
            ZnBZakZ4eEVOVDFJWVk1VVhiR1Rxb0JjRHpnCndIeDlzYXd2d0NrYmxnd3NYbnE0
            VDFwYkFzK1IxdEdRTkV1QUlPTXZDa1UKLS0tIER3M0xvQUxDQ2FnUm5wRWJVWUpm
            cUtrb1hRNXBkZk00aUNHUWhaMFM1YWsKbtABBqb1Y4Bcevqcyma3X7Ty4F4TV2zr
            ByA/j4GGsfgqqgCLbkbA8WeeOH+n4OzEJCHFCwKphvbD8z+k//mdSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T05:50:51Z"
    mac: ENC[AES256_GCM,data:SloUUOQCfvw9aHAlAurTwDLs2Pq/Jj+jkERRB51gBEQyJvcdnbcUZyXnaefyu8pMJIjLpp9CY6L6IjEzRqK7YgSY/+35Pb2i5ZLUofRuL6w2IAEUSlp/s/dTnHLmD2ujVD8qOiLfFckjAYUE0IuC7+l2ah1sjlEtwGOkhllJsLk=,iv:GM9wf16eCw1S1tlvAIwvXEGqs/8MnOpzHXHRa2tngcg=,tag:i2Yi7LgIFgom/s5ePnT+yw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
