apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kTzeMCc1a8U=,iv:cNYs2xHZE/pFhURagG7Q3uAD2NZHmceXqkwNLxWs3BI=,tag:hhm1MU/BVC43BFx2l/ElLg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:VRgGS5114AliLeY/Et8s,iv:rW6avVIna0nZUMNKPupuOUr7S2Worp3kGLEc7k61opk=,tag:uiyQR8LQzqMiqxxB44j88Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbGEvMmNQT0FYUTJTbEdz
            eTdzQStueWpkblR4NkhDSTc2WmI4cHBscFFBClNOZ1hmMU05R1EyQjhja3ppeDQz
            T21qMTc0ZVlRNU9FSjBjRlhmTS95OHMKLS0tIFlkZGk1YXhYa3lCMGlIeEtScDlG
            ZUxEWWVKRXBjOSttNjFEMkU5L0pScTgKKCR8UEyM7e2XpmXIluQd9GUTMnr+lc9X
            skkUyStuAlbrcid/viHIByH7EsZI+9LGNyn26dSxX57Gpzmk626gqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T02:06:52Z"
    mac: ENC[AES256_GCM,data:mgPCFI2IjIxd8WqWGWdc7HExiefg4rJQGDhCh0HIqY2ffHcgNnQSGzIWCm6ZJAF3QhPvcsEdCAElTuz85MAB7srE8odHQpyT2FC2JPwTvVjQN+ZP1Y88llgziQ0+4AnuZQNaVdOZXfeElLjERXvqBUqbRNFtlScl6/mIuJ5CqGY=,iv:F+nvxds3ie3aWTUauQUxr/fD5w3Z56vLKbbEhFAmOzU=,tag:epDP7yFKjOr/mOHqTbkUsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
