apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_CLOUDFLARE_EMAIL: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBET24rTmUzZytDUlBhazBZ
            QThuMlpLNkd5T2Y4VEhlSTF6N1Rjb2JKYkR3Cjc1NWMxZE9mTm04NHQ3UUFydWtw
            SDlNeWZ2LzlOYmxTeS8ydlRyRlZ3NzgKLS0tIENqVU1JbGlXVlJBZExZRThJNldN
            Sjh3cElxZGpRV1lYRU13clE0alA3UTgKZamRY+ABahMhl3gtiEHLHx132LsFgcyl
            SUX9vLCJQLGxTN9KLb28eVWjKbKJrDTkKxM9XKqTOW/9Kwt7pqhKcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T01:02:47Z"
    mac: ENC[AES256_GCM,data:DuvNb3kWb3nx/N8XIiDnfoCYl059lhqMZERVsmUuuTNvZe+eBOXz0QsH4pLHEJvkZCD+uzUWmLjdm/ztbv7t7kV+MK3pCbmMh2vEs5tL06pbU1MSz6uKGv4xAspvv3vxvpEsCZ06GYqp8vnuwCv8y/at4QdTRpTh9hpIRS+mGaA=,iv:5wHSm1byGjRE7Uy66DG+Lzm9HZKjb6SN0+THR4CLDQI=,tag:bkc9Ha6z1rrDIAd/AgzV/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
