apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_CLOUDFLARE_EMAIL: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdW96dVA0YnV4S3RYZ0NN
            eEx6Q1NSQXk1ZnpRbFVUS1A3R2hNNEtCV21JCjh2MGZPZi9kcitTSG5QakMxdnNj
            RmZwcEk5Tm5ydjZFQkROV0tSYVR2UVEKLS0tIDVFdDcrWUk0SnV1ZEFEUk4rS1Zo
            QUcydXpaKzFaYTc2VENQTU5HMlJOalkKc/JXwENu1KL/fEFDuMU5UhWMihTdLD4i
            S9Alo9AqOJ8Ej7bAhTW73nLl9ZCaFQfsgyuTqE7FIJCiYr0p2tQzmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T00:10:49Z"
    mac: ENC[AES256_GCM,data:xzCoPRz4kAbcE+TIjhyJX/XsAC6VBZtJKo72y94bvPJhPsuyf99vcRUZHUvAQhzmpxmR4QtBYm4EyRzx9tmSHDaD0LQ83xU4lqjyawic0bj6bSJbszjTa1gynpjM7dq0xhBEuWi5l9rpFkUCuFSLkWTlVlyhU2NJu8DdIckWrV4=,iv:z/MNX6XeSbE4ktYn3jLF9dq8XOjsJXddwPI20TQe9Ew=,tag:3cqds11H4dx6sQX9ke3XbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
