apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:f+zarv+s5Vw=,iv:iKzeBd3RCQjEfSgsHow1vbLSxjUuH1l+9jTCPvMMUYM=,tag:9vbx/86TZhAoGNhA2gePxA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:v4oUf91L8Bjp0qTFoPP7,iv:BjqiBmKbJJ/z1RH55CStr0f8IUKP1ccb5NvLT4fG+Mw=,tag:eYEm1a4krWkrhDZO4gm2cA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdzRKbEE0MTAwbXhyWm9F
            TDFFZnd0QVJITUtTcmJpZlVkNVAwY3p3bFRJCkx2cFpBTmw0RmdwcHFhZUEvYmp6
            RS9scTJaQUtwVStVMWpEWFo1VHhYZXcKLS0tIEdsaTZ2dEttN2VRTWJ0UGxReFBt
            ek9ibkc2dFIwV01ZSXpQVnVMMnI3T0EK7mYOGm41UR5BroeAmIc8DkBo/X8DMC12
            Y/pbZg570JcnYQFdQLysMQuClhnHKeqDPT1Dfm6t3xxPOFsMIMtQxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T03:16:01Z"
    mac: ENC[AES256_GCM,data:Q4jzfFf2W6BJVkNgoxhzr+fB8TA/gl/W2uM5YxkH5V1hDSaYjwRfnN1DWz+n3naiBpFHJnnX5ehRAWKZO58DSsh3c3N5EvUvXADK/IAIS7uQSzeJptC5cvn7wq3XYr/RcX/+YTrfPLjl9bIh7t+msgejVtzTYe3KGZz+VB+Rnk0=,iv:fE7wwNyDQ9QBcfFlL+RSZnTkvME9I+kiPgXsGjfxmIY=,tag:hHbbKczH5rjbT1Y33YlUYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
