apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:BO0TbKvKMq/+HXfTtYoYquXo/+iWhcIx,iv:JNs5zpBtzLtMN1rRcQ09RQzw3hjvE48Y63o/khHwtJs=,tag:CD3j1Ag90RkagyUMp5jYkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdlhJcGs4QkZlR2hBUFhv
            NHRHTVBjNkI3RG1vN3Y0YlYwSlExZXNRTDFJCjIvZHJLZGowcHB6VmNKc2JFWExP
            ZmZqMisvMDNTQkt2RGtnZ3NrdEhWZ3cKLS0tIGxjRm9ML3QxWjZxeEV0N2hxVWM4
            ZTJ5bDFjNHVDNFd5UE1JdDM0V2Znc1UK9cMougg8QyPvuy8NPjcuWlXtV6x4rjoV
            H5yOFLyqfrQD+ElD722AaQRSlICzW8VfGcwOrXShJ7dzDD3dpgm64Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T02:06:50Z"
    mac: ENC[AES256_GCM,data:cozPEDLK5M5aPxyO1bKVxS7HxcasG2fdztgA7a5zJgBXiB48gMtomY9IHcEw66sR0WiCfmbCHFvCBlmrTisDvqJS77/ZT3eVTOEGdOmtk18i/ygWHGTLy7pO+5wAi6KnMXhiXZFu3b4x5wPLA+a8LlZV6PO+Gm2+/mw+0aInMCE=,iv:d31HB6biu6lKfEQLVzn7yaxYyfOyTrvj+3HuCfCjvIw=,tag:XqkAjq6SQAyVAKFJ5mtPxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
