apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:oG8KPPvHyXVmJm98kmqSMlmxfP57VINO,iv:cS4FL9qj3U8Q1yUL6DwmzyIdFsqFtAh4zcg8Avr96P8=,tag:zASwS8VCa2yVPGW1We98+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTzBscFl4aHBTUEV1NVBL
            aDZqQS9qMWNQR3JWZzhWM0ZJK2h1eGw2TmxjCkRCTzBBM1ZsZzQwSHpqRkJxa1Z4
            djhjRmZOUWxVRzJ0Y3BOeFB0S0lpUzQKLS0tIHF6RjgzeHA1RGtpSjRKYkhxNnRB
            a2R1QU9pU1ZrOFFxM21ueS9Zc3dBak0K1kt3NVltdz8Jz0imaIXkg+tv1eM5ujOG
            NXLX98zZN/YMYSGXkuEsxWBDttOMIRt+b15e7rgbJiJ5oCyzstraPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T05:50:50Z"
    mac: ENC[AES256_GCM,data:hRNIr77oF41UHAj9DfsnUA6/bRNcyofagtCk2LMDM+NKUryeL8+kXHOmpACnD+AAj6quuev3VEnqs2dhi6+NqIrXmnaqXWaJQAKudmJsJqYW/Da4px9lBgFn61HbdGCv5MXVHh4zWEId/5UxzYAWsA7ejSsfpnBxyMIcZKp4F0g=,iv:Qa0iFQb0Xd/Qf4YpYbUs6LLTxhfl8Y7wmJz5ln2VCM4=,tag:RGul4hxfmcVCIlquiA0h6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
