apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    username: ENC[AES256_GCM,data:m+FvupyE0jDAADB8j98Gxg==,iv:wPl7VdE7tekWR0a6mT+QrPyuadVFHk1hvaO03hqgwl0=,tag:CWu1s8sLlCLfHNCU7k9waQ==,type:str]
    password: ENC[AES256_GCM,data:pxsBxa0fqT0d7j32liai32wJOag=,iv:qmpCZE+P1Lflft8sKpr7L7ntEnS9fsCGNHpLzU72Vck=,tag:UD9NZeiYuIavM0V+Lo7vMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybmU5RkpmTGZPM3l4citT
            c2tuakRQTEpxV2QyamZTR3NrS3pxUTd3Y1RVCkxpRkhsUXdBdU4vaHNEN1lheUNy
            MjN2cEM3VzAyaHFCRFVabk5pcUZRZEUKLS0tIExSSjM5SHhMZElQVHlHZTNIOUFI
            UlJhVXJ5alRSMG5nR0R5alVoQXcvR2sKqcSbwcIm93JU8JqPtx2iaeQGLZebTxzP
            s1MuJAKGKqD4GnjEx3XmQ3rkJ0go0DHypVarY+YfsI6I0Nak8NskIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T22:01:38Z"
    mac: ENC[AES256_GCM,data:8bqDd1/wtcGblD+Au8AQexvkSdwNbMcQqFbq2yMf3zp+LdCHnrM9g9C+q5LCZKL4tXEj/FFPCHvBODggY6e1axWCPqw9UbWTpShatvf5tfh0P5gcw++/+Gr+PFQMwk+WIuKzerUFXc+HQ/fxPnncApuFT5uqpFt0jyfyibpuCOE=,iv:VedioLUAekXDblgUbxf+/FRG7I0nftTyRAMIvSw/hws=,tag:H3vtQzJRnJGTczIX9Tk7Ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
