apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    username: ENC[AES256_GCM,data:Z+2UXRXoTTe6j+KuqwMBQQ==,iv:Ro59/50TnmfYB6utDQXaDjP0v2mewKYd97BpaH89/VY=,tag:+RzQ7mVneRBmVRL5kLEeNA==,type:str]
    password: ENC[AES256_GCM,data:CYKWcN+I+o23q8xeRh4pnp1BOXw=,iv:e4jBMr3l4A/5jPSHGz8rV8JaaZglZR0K9idbTJzNsjI=,tag:hfdjyMgkwVsXm61RXdFNlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRGVieWh4VUFRQ3IvRTFB
            QWdIdXl4NWtKYzZVMm1vWUZuSzRTRkVKWlFFClZjU3lGOFl5QkhSYy9mQjVFV1k2
            VjZvV1YwNGFJaVNUZmljVzFlZFB1a28KLS0tIEY1Nk5BcGpIMFgxKzdNVTFMcVN3
            alM0Ymh3T1A2azFuQnNWVUR0a1JHZkkKkQXhkgpe8UDpFGNz4TzihORL5NwhaUMa
            qMfUbBMjYWGa9a1kgYlXtz2k5dAMRwoGmndXSLV/dwGabI/nO/b7bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T03:29:55Z"
    mac: ENC[AES256_GCM,data:YN/LRxzOg66T3TZQvPEtMt8puN18GbM9VYwtL+rX7xU4KKlb6PMbBb4pSZ7b9491YJpAOZJyiOtlqF42KBEXdlf+vvN+PhCyGpDqdith5i+TE28V5MliNiN1v95lVWA/JljTERk0IV1HCDGoOAFOqlfwvLIG9dO28G/oHbDm4hY=,iv:1ugQSCqAWMUmcOyuThCO8IahJRUs0L50qgFbv1zHV7g=,tag:9so50qZFvYq5/Au9d+MeHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
