apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    username: ENC[AES256_GCM,data:3fzjFROG3uYRtfsAXGQfww==,iv:xKhiI5YeuEhbgy3Iek5+64AbyP9RtSbrN9ePIwUvVag=,tag:zVyBlze0KAoteaIrp3cxGA==,type:str]
    password: ENC[AES256_GCM,data:GAN8RBqwRFnamvGL10+cTMH/gUs=,iv:XwJqHsMGT/8tBBKnN4ldVw0dva69FLSPOYDbDzii9RA=,tag:DTExmaC7dHjDOwZ3hRDoQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN2NSSkJxWVZXNGpiNFd3
            OWdhb1FzNzFrZkhNanU5ZlVjanVabTUwaHpJCjg3dUlyblMzNDVrL1V6N0ZJNkZs
            VlNISk41ME1QdUVKUDFuOFlaNGo1Y1UKLS0tIEdpOFdUZ1B3dEVVU2tmV292K25T
            ZC9wVWpBZ3hzTEppYy85VlVISEtjUlEKbsyxwUHU2SpqWmhMyOHkS1fQh3Bb2jVg
            DIb4QWaisB2LEEzhgLRF0mPk5NOAwbeLRnhfACyJm4w/eTUCwDCp9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T06:15:44Z"
    mac: ENC[AES256_GCM,data:FyyHmCbgS5pd85VudrL/jPR9lOnHnaZDVouB2WGv9o8jEqs6hrN6HS9dVkiooing7WSAc+j+Tpcv+Tbz8Fkt8a7mI98mU4rdDS+/GfJeIsK7AqSVcXM35AYUAmGz7VJGjldFV2Jyry9X1VVLQ2BjW7EofKJf5l4m1fUNeqmwYdg=,iv:32Bv6v7byiV86uqjdKeNSE6x3DZkHdrKD9GuWRs4a6k=,tag:XJtd+1yEy8N7aoMSbRu/fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
