apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    username: ENC[AES256_GCM,data:Aydbj0KjXSschwKaFpO8/g==,iv:kiDN23Zkaj8cAxu3nPPiHn8qc6i8QCV8zkd2ZJNLqFI=,tag:6rk01yoJbexIVlhJo3fXGw==,type:str]
    password: ENC[AES256_GCM,data:bfTUFx2tI/f4OL6tFwvqkF+HDog=,iv:sTnr41G1ZnntSSNHC/L3CiSgLoi7aNoBNyCYSBcu1pM=,tag:ZFQAZUCC+h3mc3TPjE2EVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNFErRmhjdnJrdUFVSjFJ
            bnB2VitIY2dRZHhHUGQyZVdqWms4aGo0Q1RBCnNWaFlLL2h5L2c1QjNtVUQwTngy
            cWdSczVWU3JoWG82WFZ5SWJxSmdKbDAKLS0tIDN5Wk4rWWlZanlUY2FzL0VNS3c4
            aVQrUnlmYzJwYUNvZW14eXNDakRPT0kKDJZ6HK27PCpB75ITqBGPuUGFKqn9rHMR
            zUJi3OyuWOxIeUjwiozcdBzNNmRSvb1KkEMQaNYD87lOY7kUchQ6pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T21:16:46Z"
    mac: ENC[AES256_GCM,data:gjxErApeekGHZNlrl/lzbD7SwBqh3XrajAlEwRL18VXFe1mZUXivDZyVHFbnaCHn3T4jnnW/cu+/J5y39c1PC4FamawpjnBwjE+2HjCT/W1FYIBAzxzEzm3SWtNK3qR/kr2+TP/t2byLd+Z1WZOt6eFymxmhxRM5mYHo7V/2xs8=,iv:ozOC9t1oQiCmxufMWb43FqyYYRHfV09AHefBmx8b6uc=,tag:v4uhSUKbyO32sG3WKo0O0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
