apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    username: ENC[AES256_GCM,data:D2ubIm75FT9v8D8hjqAhzg==,iv:AWYDKX1OQFba3WDUV58rpnhKugGc3YtuFS9qAE21umE=,tag:2xuvJ5VvKytbEFf2cn+rqA==,type:str]
    password: ENC[AES256_GCM,data:8j3wFuPOIckfibuopGS/HQwanNE=,iv:FKH0m0jMG0noohrjwRVbcCYq9WVqKIgzvzQSoXFm3NY=,tag:nsf8KgdM+BdBMqdiWtOj7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjc1BtWXg1OStscHBPL09v
            VGo2Y21uNkd1RTdxeGd4ZGt0c0ZnSzhiRWpRCmRqUHAwU0JBSEQxay9iYUN1RFJm
            ZDB6dTlKSm5pNjJ1ZVkzVXE5aXBLNTgKLS0tIGg2L25HeXZ1L2Nuc2pZRUs1eGpq
            cVpvNjVQNWlsZjF3N1crTjZtTTFuMm8KrGwyXHS1gB0BuHRe14aW2g856eJ2LjfX
            baOFb9j055QeOYx4gDu/dLNqTh3LXXaZxGICuIpuJJLc4YUHiD9hYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-24T02:31:22Z"
    mac: ENC[AES256_GCM,data:Os0bDEITNR4osE3AsIMQz8ajDRkJx7/N8WY4ZlI6ZYhGdWnWiqmgYDSLXbxxB/EG54YJYbNyP7/HHDe81QjAqffP7526yZ3K5rHmGRUXfBVp6mH9Lp8nnTBWn/yTuWF3OvQoNehekT97hXUvj6JTZH2BRtSNQAo8G5Q6ogoiVAE=,iv:VTTLwNA5+A4gy0vCqiz8Nn888M9KWP74crus4cOQqLg=,tag:eV49OKVNGEd+Gs1nxbnT6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
