apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    username: ENC[AES256_GCM,data:sES0bLMJXcJ6SXrbxlwZQg==,iv:7A2R2OD2cN8o3kqVAkt0uPr4DZSkhNPZDX22rekjjIM=,tag:jCyVJ5Ab3UC9VtmPOS8bdw==,type:str]
    password: ENC[AES256_GCM,data:++S5QH/d0GZWe9FKT3ieKQI2E3Y=,iv:inEMwtR7QTqEqmksnTZkr7ecD+HXWPDQCeOvdJkpnWY=,tag:jdLvGSUB8mreJtrszQsu/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwT1BVYnB0dUdqdFBDa1RF
            Mm5peTVlMDJZaGxpNGczL0dHV3lGL0dRRTBvCkRtTTJNazBSN0dyQTM3NFcwWUF1
            ZkJsTUg5K1BOUGk2SWhjR0FNbXJVTncKLS0tIE1MNzA4YS9HM0pyYnE2ZmthcXht
            NU9MUHFZd1V0elpqZW5GMUhFU2F5YUkKxmiA7kKFfjfKpSqWmR6jiZ1inRfxWrT1
            skL/7NctNmaO4PNwYawR3Hg0+BTGKYw7KLg4H/yR4F7+N+WDoUt9Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T05:45:42Z"
    mac: ENC[AES256_GCM,data:+FOuIn6B5VAeDyWYQyS8xMyXcGtiLY3Ds2sInjd1o392XS+IqHclx+EZOyKKYYNCllfgs+nIcCuCatFj0iXQvT4Pf/lUKpSPjtH0oqHWQJ4G6jlRrapDoenZ3ORX+1TiyfDj3Oamv/qPn88NiIW1MZQfc+JRlW1zP+JB9mCLXhw=,iv:sCoIhErnlMUVsjy9w43VVM/tzwlQvPIYHsuidBsKDQE=,tag:6Au9uK65hOQFSzrQIGNlTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
