apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    username: ENC[AES256_GCM,data:R0wtkwcsXvLZ7Ba7uOcWWA==,iv:7p375f7m99hPtVDDShEl5WsbjTo4nunEYTj/GI8nUao=,tag:rVbW5teeq71uKqDIlFlV6g==,type:str]
    password: ENC[AES256_GCM,data:OMMr70v26NFyU8gbMf/OrGDsFaE=,iv:nhb3TcesX4lryd0Q0XVmWhFcRgv/23FDQcnw7r8OyJ8=,tag:KjeTuAbPe1wTc7+DZkSFAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jytkscy2ls0k8gexantxv6hm6gj0ttjpxvcnc5zwr5xmakkfsypsa4eg5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cDA3KzlWODBOeXU5YmhZ
            M2p4cjRBUzNMQ1lESThxSlpPYkk5K3RTcUIwCmh0V3pvMC96dnVtZmliaGtocU9X
            U21Kdm4xOURhb214VDJ4WGdXYkliM1kKLS0tIHEzbTJFK0NGSzF0ZGVSeXQyamhs
            ODNUMVQ5Rm9DTE84T09UNUZBdnMxQWcKXu/oA4G9cxBx2IbG4+d7lcgpKz6yEZl7
            OCsxFqH4ecVznPBgIE3Y128je905gbTqnebRut/JXcs5bpNxUHagLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T04:16:44Z"
    mac: ENC[AES256_GCM,data:6QqulUkkaBEdQqfSNUC8JkdeqDqzrobRSBopYmneZ/0QN+Vb2zRq5pXUMTKd9TswzRkW4RhAJjooZgwGHnvX5ae/6TFMUAXQyXxmdYUptekguObOeEZxs5HUHeJZM3j2mprLlW7fEXzcGCFbHsEi1FLhK6H7ZrJc8WwxDu9xHKQ=,iv:CAj2hulzxKll3RncpJUYrbZ6vvd3LojtSRvvRhM1MW4=,tag:m63/zPrjqzMnEJsJi6gAsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
